.TH "apk-thumbnailer" "1" "April 23, 2019" "" "apk-thumbnailer"
.SH "NAME"
apk-thumbnailer - program to generate thumbnail for apk.
.br

.SH "SYNOPSIS"
\fBapk-thumbnailer \fR<apk-path> <output> <thumbnail-height>
.br

.SH "DESCRIPTION"
Create thumbnail from apk.
.br

\fBapk-thumbnailer\fR is for creating apk thumbnail.
.br

It uses apk icon to create thumbnail.
.br
